openapi: 3.0.3
info:
  title: Laxmikant Swain
  description: |
    Portfolio website for DevOps Engineer
  version: 1.0.0
  contact:
    name: Laxmikant Swain
    url: http://localhost:5000
    email: laxmikantswain93@gmail.com
  license:
    name: Laxmikant Swain License
    url: http://localhost:5000/terms
servers:
  - url: http://localhost:5000
    description: Development server
paths:
  /api/users:
    post:
      summary: Register new user
      description: Validate new user and create new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                  minLength: 6
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                        example: John Doe
                      email:
                        type: string
                        example: john@example.com
        '400':
          description: Bad request, validation errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        msg:
                          type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string                